apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodejs-sample
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nodejs-sample
    template:
        metadata:
            labels:
                app: nodejs-sample
        spec:
            containers:
                - name: server
                  image: ito/webappl
                  imagePullPolicy: Never
                  ports:
                  - containerPort: 3000
                  env:
                  - name: PORT 
                    value: 3000
            