apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nodejs-sample
spec:
  selector:
    matchLabels:
      app: nodejs-sample
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nodejs-sample
    spec:
      containers:
      - name: nodejs-sample
        image: semimatadocker/nodejs-sample:v1
        ports:
        - containerPort: 3000